config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: %i[index show edit create destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[index create destroy] do
      collection do
        get 'followers'
        get 'followed'
      end
    end
  end

  resources :groups do
    resource :group_users, only: %i[create destroy]
    resources :notices, only: %i[new create]
  end

  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :notices, dependent: :destroy

  has_one_attached :group_image

  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 200 }

  def get_group_image(width = 100, height = 100)
    unless group_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      group_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    group_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.users = [current_user]
    if @group.save
      redirect_to groups_path, notice: 'You have created group successfully.'
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
    redirect_to groups_path unless @group.owner_id == current_user.id
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: 'You have updated group successfully.'
    else
      render 'edit'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image).merge(owner_id: current_user.id)
  end
end

app/views/groups/_form.html.erb
<%= form_with model: group, local:true do |f| %>
  <%= render 'layouts/errors', obj: group %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control name" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :group_image, class: "form-control-file user_image", accept: 'image/*' %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "form-control introduction" %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th>introduction</th>
      <th>メンバー数</th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_group_image(50, 50) %></td>
        <td><%= link_to group.name, group, class: "group_#{group}.id}" %></td>
        <td><%= group.introduction %></td>
        <td><%= group.users.count %></td>
          <% if group.owner_id == current_user.id %>
            <td><%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success edit_book_#{group.id}" %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Edit group</h2>
    <%= render 'form', group: @group %>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>

      <%= render 'index',groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create group</h2>
    <%= render 'form', group: @group %>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User_info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th>introduction</th>
            <th>メンバー</th>
          </tr>
        </thead>
  		  <tr>
          <td>
            <%= image_tag @group.get_group_image(50, 50) %><br>
          </td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <% @group.users.each do |user|%>
              <%= user.name %>
              <br>
            <% end %>
          </td>
          <% if @group.owner_id == current_user.id %>
            <td><%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success edit_group_#{@group.id}" %></td>
            <td><%= link_to 'Notice an Event', new_group_notice_path(@group.id), class: "btn btn-sm btn-success new_notice_#{@group.id}" %></td>
          <% end %>
          <% if @group.owner_id != current_user.id %>
            <% if @group.users.include?(current_user)  %>
              <td><%= link_to 'Leave This Group', group_group_users_path(@group.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
            <% else %>
              <td><%= link_to 'Join This Group', group_group_users_path(@group.id), method: :post, class: "btn btn-sm btn-success" %></td>
            <% end %>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>