config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: %i[index show edit create destroy update] do
    resource :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end
  resources :users, only: %i[index show edit update] do
    resource :relationships, only: %i[index create destroy] do
      collection do
        get 'followers'
        get 'followed'
      end
    end
  end

  resources :groups do
    resource :group_users, only: %i[create destroy]
    resources :notices, only: %i[new create]
  end

  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  def search # rubocop:disable all
    @word = params[:word]
    @model_name = params[:model]
    @search_results =
      case params[:pattern_match]
      when 'exact_match'
        @model_name.classify.constantize.exact_match(@word)
      when 'forward_match'
        @model_name.classify.constantize.forward_match(@word)
      when 'backward_match'
        @model_name.classify.constantize.backward_match(@word)
      when 'partial_match'
        @model_name.classify.constantize.partial_match(@word)
      end
  end
end

app/views/searches/_results.html.erb
<h1>
  <%= "#{model_name}s search for \"#{word}\""%>
</h1>

<% if search_results.blank? %>
  <h1>results not found.</h1>
<% else %>
  <table class='table table-hover table-inverse'>
    <% if model_name == "Book" %>
      <thead>
        <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% search_results.each do |book| %>
          <tr>
            <td>
              <%= image_tag book.user.get_profile_image, size:'50x50' %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </tbody>
    <% elsif model_name == "User" %>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% search_results.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(50, 50) %></td>
            <td>
              <%= link_to user_path(user.id) do %>
                <%= user.name %>
              <% end %>
            </td>
            <td>
              <%= user.introduction %>
            </td>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
<% end %>

app/views/searches/_search_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="search-form col-md-8">
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.search_field(:word) %>
        <%= f.select :model, ['User', 'Book'] %>
        <%= f.select :pattern_match, { "完全一致" => "exact_match","前方一致" => "forward_match", "後方一致" => "backward_match", "部分一致" => "partial_match" } %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<%= render 'results', word: @word, search_results: @search_results, model_name: @model_name %>